// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIOZDc69UwyOtiY4k34MI49rnTbONT4qw',
    appId: '1:1053965638081:web:5aeedae28fb392373ab740',
    messagingSenderId: '1053965638081',
    projectId: 'uco-kiosk-app-6270d',
    authDomain: 'uco-kiosk-app-6270d.firebaseapp.com',
    storageBucket: 'uco-kiosk-app-6270d.firebasestorage.app',
    measurementId: 'G-NH6NXVDJPJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-1IKJGWPQhZfhwSuE7hIj2fIRkMwpNrs',
    appId: '1:1045517832974:android:ce8f126631e55a91037d5f',
    messagingSenderId: '1045517832974',
    projectId: 'uco-kiosk-personal-f92b6',
    storageBucket: 'uco-kiosk-personal-f92b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4XLdCzGvPMAXiyZ3Tbuf7roUGMIYeZM8',
    appId: '1:1045517832974:ios:db8ce2bfdf1bf327037d5f',
    messagingSenderId: '1045517832974',
    projectId: 'uco-kiosk-personal-f92b6',
    storageBucket: 'uco-kiosk-personal-f92b6.firebasestorage.app',
    iosBundleId: 'com.example.ucoKioskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx_h8hLRFUFa4BaDo6CpObRM0CgwBGudk',
    appId: '1:1053965638081:ios:5b72f8d691d48bcf3ab740',
    messagingSenderId: '1053965638081',
    projectId: 'uco-kiosk-app-6270d',
    storageBucket: 'uco-kiosk-app-6270d.firebasestorage.app',
    iosBundleId: 'com.example.ucoKioskApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIOZDc69UwyOtiY4k34MI49rnTbONT4qw',
    appId: '1:1053965638081:web:e59c0bfc9e657f983ab740',
    messagingSenderId: '1053965638081',
    projectId: 'uco-kiosk-app-6270d',
    authDomain: 'uco-kiosk-app-6270d.firebaseapp.com',
    storageBucket: 'uco-kiosk-app-6270d.firebasestorage.app',
    measurementId: 'G-8YL5TMNYSL',
  );

}